const form = document.getElementById('travelForm');
const generateBtn = document.getElementById('generateBtn');
const resultsContainer = document.getElementById('resultsContainer');
const statusText = document.getElementById('statusText');
const aiResponseDiv = document.getElementById('aiResponse');
const deepLinksContainer = document.getElementById('deepLinksContainer');

const BACKEND_URL = 'http://127.0.0.1:8000/api/chat';

form.addEventListener('submit', async (e) => {
    e.preventDefault(); // Stop page from refreshing

    // 1. Gather all data from the form
    const source = document.getElementById('source').value;
    const destination = document.getElementById('destination').value;
    const startDate = document.getElementById('startDate').value;
    const endDate = document.getElementById('endDate').value;
    const budget = document.getElementById('budget').value;
    const travelers = document.getElementById('travelers').value;
    const interests = document.getElementById('interests').value;

    // 2. Construct a detailed prompt for the AI
    const userPrompt = `
        I want to plan a trip from ${source} to ${destination}.
        Dates: ${startDate} to ${endDate}.
        Budget: ${budget ? budget : 'Not specified'}.
        Number of travelers: ${travelers}.
        My interests are: ${interests ? interests : 'General sightseeing'}.
        Please provide a personalized itinerary and recommend the best transport options.
    `;

    // 3. Update UI to show loading state
    resultsContainer.classList.remove('hidden');
    statusText.innerText = "Analyzing routes and building your itinerary...";
    aiResponseDiv.innerHTML = "";
    deepLinksContainer.innerHTML = "";
    generateBtn.disabled = true;
    generateBtn.innerText = "Generating...";

    // 4. Send request to the backend
    try {
        const response = await fetch(BACKEND_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ message: userPrompt })
        });

        if (!response.ok) {
            throw new Error(`Server returned status: ${response.status}`);
        }

        const data = await response.json();
        processBotResponse(data.response);

    } catch (error) {
        console.error("Fetch error:", error);
        statusText.innerText = "Error contacting the travel agent backend. Is your server running?";
    } finally {
        // Reset button
        generateBtn.disabled = false;
        generateBtn.innerText = "Generate itinerary";
    }
});

// 5. Parse the AI's response and JSON blocks
function processBotResponse(fullText) {
    statusText.innerText = "Here is your personalized trip plan:";
    
    // Look for the JSON block generated by the Python backend
    const jsonMatch = fullText.match(/```json\s*([\s\S]*?)\s*```/);
    let cleanedText = fullText;
    let jsonData = null;

    if (jsonMatch) {
        cleanedText = fullText.replace(jsonMatch[0], ''); // Strip JSON out of the text
        try {
            jsonData = JSON.parse(jsonMatch[1]); 
        } catch(e) {
            console.error("Failed to parse AI JSON block");
        }
    }

    // Parse the markdown into HTML so tables and bold text render correctly
    aiResponseDiv.innerHTML = marked.parse(cleanedText.trim());

    // Insert the booking cards if JSON data exists
    if (jsonData && jsonData.has_options && jsonData.options) {
        jsonData.options.forEach(opt => {
            const card = document.createElement('div');
            card.className = 'booking-card';
            card.innerHTML = `
                <div>
                    <strong>[${opt.type}] ${opt.name}</strong><br>
                    <small style="color: #64748b;">${opt.price} | ${opt.duration}</small>
                </div>
                <a href="${opt.link}" target="_blank" class="book-btn">Book Now</a>
            `;
            deepLinksContainer.appendChild(card);
        });
    }
}